version: "3.8"

networks:
  k6:
  grafana:
  prometheus:

services:
  prometheus:
    image: prom/prometheus
    #    entrypoint: /bin/sh
    #    user: root
    command:
      - --web.enable-remote-write-receiver
      - --enable-feature=native-histograms
      - --config.file=/etc/prometheus/prometheus.yaml
    networks:
      - k6
      - grafana
      - prometheus
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus.yaml:/etc/prometheus/prometheus.yaml
      - ./prometheus-data:/prometheus

  grafana:
    image: grafana/grafana-oss
    networks:
      - grafana
      - prometheus
    ports:
      - "3000:3000"
    environment:
      - GF_AUTH_ANONYMOUS_ORG_ROLE=Admin
      - GF_AUTH_ANONYMOUS_ENABLED=true
      - GF_AUTH_BASIC_ENABLED=false
      - GF_SERVER_SERVE_FROM_SUB_PATH=true
    volumes:
      - ./dashboards:/var/lib/grafana/dashboards
      - ./grafana-dashboard.yaml:/etc/grafana/provisioning/dashboards/dashboard.yaml
      - ./grafana-datasource.yaml:/etc/grafana/provisioning/datasources/datasource.yaml

  k6:
    image: grafana/k6:master-with-browser
    #    entrypoint: /bin/sh
    #    user: root
    networks:
      - k6
      - prometheus
    ports:
      - "6565:6565"
    environment:
      #----------------------------- prometheus config ---------------------
      - K6_PROMETHEUS_RW_PUSH_INTERVAL=5s
      - K6_PROMETHEUS_RW_SERVER_URL=http://prometheus:9090/api/v1/write
      - K6_PROMETHEUS_RW_TREND_AS_NATIVE_HISTOGRAM=true
      - K6_OUT=xk6-prometheus-rw
      - K6_PROMETHEUS_RW_INSECURE_SKIP_TLS_VERIFY=true
      #- K6_PROMETHEUS_RW_STALE_MARKERS=true
      - K6_BROWSER_ENABLED=true
      #----------------------------- browser testing ----------------------
      #- K6_BROWSER_HEADLESS=true
      #---------------------------------------------------------------------
    command:
      - --cap-add=SYS_ADMIN
    depends_on:
      - prometheus
    volumes:
      - ./scripts:/scripts
      - ./prometheus-data:/prometheus
volumes:
  grafana_storage: {}
